### ISSUE TITLE
Sorting primitive logic processing functions

### ISSUE THREAD

**Issue by calveym** [pycollabproject/realprice#13]
Hey guys,

I'll have a look at writing up the base code for the mean, median, location and range. I'll be collaborating with sturdy to make sure we don't create conflicts.

**Comment by calveym** [comment]
@sturdyplum

**Comment by sturdyplum** [comment]
hey, just saw this, right now I'm working on the iqr method. I think that how it's going to work is that the method will be passed a dict with the information needed and return the iqr.
