### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by jakeherold** [pycollabproject/realprice#2]
Hello all! I'm super pumped to start! Can we get a to do list of things to get going on?

**Comment by calveym** [comment]
Haha great that you are keen to start! I think we should let the latest thread sit on the sub for a bit for everyone to get on board, and then we'll go for it! Check out the goals I have outlined so far, and see if there's anything you'd like to add.

**Comment by LMCMLJ** [comment]
http://pycollabproject.github.io/realprice/ Nicer list there

**Comment by sturdyplum** [comment]
just a question but what crawler library are we going to be using? I want to learn it asap.

**Comment by czotomo** [comment]
We'll wrap APIs with 'Requests' and re-serialize returns with 'json' (zillow returns XML data, our backend wants it in json). I am not sure which XML module to use to parse XML yet. Of course we will use os, time and maybe few other standard lib modules too. For testing - unittest module.

**Comment by sturdyplum** [comment]
Ok so if the backend takes the data in json then processes the data to find
the mean, medium, how would they give the processed data to the ui team?

**Comment by czotomo** [comment]
They'll issue it in POST request probably. I dont really know anything about Flask, and looks like our backend is going to use it.
