### ISSUE TITLE
Median code bug

### ISSUE THREAD

**Issue by calveym** [pycollabproject/realprice#23]
Hey @sturdyplum , I just discovered a little bug in some of the median code you wrote. In line 45 of functions.py, you attempt to create a slice with what could be a float [(totalInstances - 1) / 2]

I know you have that if/ else statement to avoid that, but the interpreter is going straight through it and returns it as a syntactically invalid input, so we will have to find a way around it.

**Comment by sturdyplum** [comment]
maybe I could cast it as an int

**Comment by sturdyplum** [comment]
ok I think that should fix it check my pull request
